### ISSUE TITLE
"Object reference not set to an instance of an object" when importing BlogML file with no "tags" elements

### ISSUE THREAD

**Issue by simonech** [Shazwazza/Articulate#117]
If the blogml (or some posts in the blogml) do not have the tag element, the importer crashes

```
 2015-11-04 17:02:09,299 [P7920/D22/T138] ERROR Articulate.BlogMlImporter - Importing failed with errors
System.NullReferenceException: Object reference not set to an instance of an object.
   at Articulate.BlogMlImporter.ImportTags(XDocument xdoc, IContent postNode, BlogMLPost post) in X:\Projects\Articulate\Articulate.Project\src\Articulate\BlogMlImporter.cs:line 334
   at Articulate.BlogMlImporter.<ImportPosts>d__11.MoveNext() in X:\Projects\Articulate\Articulate.Project\src\Articulate\BlogMlImporter.cs:line 269
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Articulate.BlogMlImporter.<Import>d__8.MoveNext() in X:\Projects\Articulate\Articulate.Project\src\Articulate\BlogMlImporter.cs:line 84
```

**Comment by simonech** [comment]
actually the problem is when a post doesn't have an id in it.
