### ISSUE TITLE
Missing Logo or Banner Causes Error in tags controller (v2.0.5)

### ISSUE THREAD

**Issue by JasonEleventeen** [Shazwazza/Articulate#164]
at Umbraco.Web.ImageCropperTemplateExtensions.GetCropUrl(IPublishedContent mediaItem, Nullable`1 width, Nullable`1 height, String propertyAlias, String cropAlias, Nullable`1 quality, Nullable`1 imageCropMode, Nullable`1 imageCropAnchor, Boolean preferFocalPoint, Boolean useCropDimensions, Boolean cacheBuster, String furtherOptions, Nullable`1 ratioMode, Boolean upScale)
   at Articulate.Models.MasterModel.get_BlogBanner() in X:\Projects\Articulate\Articulate.Project\src\Articulate\Models\MasterModel.cs:line 88
   at Articulate.Models.TagListModel..ctor(IMasterModel masterModel, String name, Int32 pageSize, PostTagCollection tags) in X:\Projects\Articulate\Articulate.Project\src\Articulate\Models\TagListModel.cs:line 25
   at Articulate.Controllers.ArticulateTagsController.RenderTagsOrCategories(RenderModel model, String tagGroup, String baseUrl) in X:\Projects\Articulate\Articulate.Project\src\Articulate\Controllers\ArticulateTagsController.cs:line 85
   at Articulate.Controllers.ArticulateTagsController.Categories(RenderModel model, String tag, Nullable`1 p) in X:\Projects\Articulate\Articulate.Project\src\Articulate\Controllers\ArticulateTagsController.cs:line 51
   at lambda_method(Closure , ControllerBase , Object[] )

Adding a banner and logo removes error

**Comment by Shazwazza** [comment]
Hrm, i can't replicate this in the latest code so I'm pretty sure this was an issue with Umbraco core not performing null checks.
