### ISSUE TITLE
Umbraco.Core.Exceptions.BootFailedException: Boot failed.

### ISSUE THREAD

**Issue by khraibani** [Shazwazza/Articulate#444]
Update umbraco from 8.18.12 to 8.18.13 I am getting the folowing error
Articulate version 4.4.0

`Umbraco.Core.Exceptions.BootFailedException: Boot failed.

-> System.MissingMethodException: Method not found: 'Void Umbraco.Web.PropertyEditors.MarkdownPropertyEditor..ctor(Umbraco.Core.Logging.ILogger)'.
  at Articulate.PropertyEditors.ArticulateMarkdownPropertyEditor..ctor(ILogger logger)
  at DynamicMethod(Object[] )
  at LightInject.PerContainerLifetime.GetInstance(Func`1 createInstance, Scope scope) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 6169
  at LightInject.ServiceContainer.EmitLifetime(ServiceRegistration serviceRegistration, Action`1 emitMethod, IEmitter emitter) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 4656
  at LightInject.ServiceContainer.<>c__DisplayClass153_0.<CreateEmitMethodWrapper>b__0(IEmitter ms) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 3856
  at LightInject.ServiceContainer.CreateDynamicMethodDelegate(Action`1 serviceEmitter) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 3777
  at LightInject.ServiceContainer.CreateDelegate(Type serviceType, String serviceName, Boolean throwError) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 4743
  at LightInject.ServiceContainer.CreateDefaultDelegate(Type serviceType, Boolean throwError) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 4705
  at LightInject.ServiceContainer.GetInstance(Type serviceType) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 3437
  at Umbraco.Core.Composing.CollectionBuilderBase`3.CreateItem(IFactory factory, Type itemType) in D:\a\1\s\src\Umbraco.Core\Composing\CollectionBuilderBase.cs:line 111
  at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
  at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
  at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
  at Umbraco.Core.Composing.CollectionBuilderBase`3.CreateCollection(IFactory factory) in D:\a\1\s\src\Umbraco.Core\Composing\CollectionBuilderBase.cs:line 120
  at LightInject.PerContainerLifetime.GetInstance(Func`1 createInstance, Scope scope) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 6169
  at LightInject.ServiceContainer.EmitLifetime(ServiceRegistration serviceRegistration, Action`1 emitMethod, IEmitter emitter) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 4656
  at LightInject.ServiceContainer.<>c__DisplayClass153_0.<CreateEmitMethodWrapper>b__0(IEmitter ms) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 3856
  at LightInject.ServiceContainer.EmitConstructorDependency(IEmitter emitter, Dependency dependency) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 4158
  at LightInject.ServiceContainer.EmitConstructorDependencies(ConstructionInfo constructionInfo, IEmitter emitter, Action`1 decoratorTargetEmitter) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 4120
  at LightInject.ServiceContainer.EmitNewInstanceUsingImplementingType(IEmitter emitter, ConstructionInfo constructionInfo, Action`1 decoratorTargetEmitMethod) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 4081
  at LightInject.ServiceContainer.EmitNewInstance(ServiceRegistration serviceRegistration, IEmitter emitter) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 4038
  at LightInject.ServiceContainer.CreateDynamicMethodDelegate(Action`1 serviceEmitter) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 3777
  at LightInject.ServiceContainer.<>c__DisplayClass198_0.<EmitLifetime>b__1() in C:\projects\lightinject\src\LightInject\LightInject.cs:line 4657
  at LightInject.PerContainerLifetime.GetInstance(Func`1 createInstance, Scope scope) in C:\projects\lightinject\src\LightInject\LightInject.cs:line 6169`

**Comment by davidclintontitanwebtech** [comment]
We're also experiencing this on one of our Umbraco Cloud sites that just auto updated to 8.18.13!

Is v4 still supported now v5 has been released for this to be patched?

**Comment by Shazwazza** [comment]
Sounds to me like a ctor has changed. I'm happy to release new versions but I currently don't have time to explore/debug this so any PRs and help are needed from the community to get this fixed.

**Comment by Jeavon** [comment]
PR for this @ https://github.com/Shazwazza/Articulate/pull/445

Patched v4.4.0 assembly attached for those with stuck Umbraco Cloud sites [Articulate.zip](https://github.com/Shazwazza/Articulate/files/14348057/Articulate.zip)

**Comment by Shazwazza** [comment]
Thanks @Jeavon, I've merged and pushed v4.5.0 to Nuget - I haven't tested it but since the build all works and your changes look good, I expect it to work 🤞😊

**Comment by Shazwazza** [comment]
See https://github.com/Shazwazza/Articulate/releases/tag/v4.5.0
