### ISSUE TITLE
Error with multiple articulate in root

### ISSUE THREAD

**Issue by wroughtec** [Shazwazza/Articulate#81]
Ok I am not 100% sure this is caused by Articulate however when I have 2 articulate blogs in the root and define subdomains to them most of the site goes yellow screen as below (have not worked out why some pages are fine and others not). If I move one of the blogs into a folder and define the folder with a subdomain then there is not issue and thoughts would be appreciated.

I should point out I have 3 blogs on this site 2 are in the root and one inside the folders although I intend to moved one of the blogs from a folder to the root.

````
Level	ERROR
Logger	Umbraco.Core.UmbracoApplicationBase
Thread	No: , Id: 26
[T8/D17] An unhandled exception occurred
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Articulate.TagsOrCategoryPathRouteConstraint.Match(HttpContextBase httpContext, Route route, String parameterName, RouteValueDictionary values, RouteDirection routeDirection)
   at System.Web.Routing.Route.ProcessConstraint(HttpContextBase httpContext, Object constraint, String parameterName, RouteValueDictionary values, RouteDirection routeDirection)
   at System.Web.Routing.Route.ProcessConstraints(HttpContextBase httpContext, RouteValueDictionary values, RouteDirection routeDirection)
   at System.Web.Routing.Route.GetRouteData(HttpContextBase httpContext)
   at System.Web.Routing.RouteCollection.GetRouteData(HttpContextBase httpContext)
   at System.Web.Routing.UrlRoutingModule.PostResolveRequestCache(HttpContextBase context)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by Shazwazza** [comment]
Thanks for the report. So that i can try to replicate, can you post what your content node structure is and what domains you have assigned to which nodes?

**Comment by wroughtec** [comment]
The site is on Azure (if this makes a difference) I could replicate this on locahost
Ok I have one domain I use as a global to login into umbraco. Then I have the following:
-Home (no domain yet but will  have the main www attached)
--folder
---Articulate blog
-node (subdomain)
-node (currently no domain set)
-node (currently no domain set)
-node (currently no domain set)
-Articulate blog (subdomain)
-node (subdomain)
-node (subdomain)
-node (subdomain)
-node (subdomain)
-node (currently no domain set)
-Articulate blog (subdomain)

I had this issues a few days ago but had not noticed what was causing the issue until I repeated adding the subdomains so i actually have a db on azure you can connect to as this is throwing the same error locally for me in VS. I don't even need to write in a correct url it throws the error straight away if this will help.

**Comment by Shazwazza** [comment]
It will be something to do with how the routing is setup in articulate with the multi-tenancy, probably doesn't cater for various complex setups - I'll test this in the next week or so (sorry, ultra busy atm with CodeGarden)

**Comment by wroughtec** [comment]
no problem I have a temp solution of putting one of the articulate blogs inside a folder and put the subdomain to the folder then redirect to the blog

**Comment by bootnumlock** [comment]
This sounds very similar to what I am experiencing

Bob Baty-Barr

**Comment by bootnumlock** [comment]
Shan, any updates on this for us?

**Comment by Shazwazza** [comment]
yay, fixed finally :)
